-- MAPPINGS OF ASTRAL -> LOVR KEYS
-- A REVERSE TABLE IS CONSTRUCTED AT RUNTIME FOR LOOK UP

return {
    Mouse = {
        MouseButton1 = 1,
        MouseButton2 = 2,
        MouseButton3 = 3,

        MouseButtonLeft = 1,
        MouseButtonRight = 2,
        MiddleMouseMiddle = 3,
    },
    KB = {
        A = "a",
        B = "b",
        C = "c",
        D = "d",
        E = "e",
        F = "f",
        G = "g",
        H = "h",
        I = "i",
        J = "j",
        K = "k",
        L = "l",
        M = "m",
        N = "n",
        O = "o",
        P = "p",
        Q = "q",
        R = "r",
        S = "s",
        T = "t",
        U = "u",
        V = "v",
        W = "w",
        X = "x",
        Y = "y",
        Z = "z",

        Zero = "0",
        One = "1",
        Two = "2",
        Three = "3",
        Four = "4",
        Five = "5",
        Six = "6",
        Seven = "7",
        Eight = "8",
        Nine = "9",
        Ten = "10",

        Space = "space",
        Enter = "return",
        Tab = "tab",
        Escape = "escape",
        Backspace = "backspace",

        Up = "up",
        Down = "down",
        Left = "left",
        Right = "right",

        Home = "home",
        End = "end",

        PgUp = "pageup",
        PgDown = "pagedown",
        Insert = "insert",
        Delete = "delete",

        F1 = "f1",
        F2 = "f2",
        F3 = "f3",
        F4 = "f4",
        F5 = "f5",
        F6 = "f6",
        F7 = "f7",
        F8 = "f8",
        F9 = "f9",
        F10 = "f10",
        F11 = "f11",
        F12 = "f12",

        Tick = "`",
        Minus = "-",
        Equals = "=",
        LBracket = "[",
        RBracket = "]",
        BckSlash = "\\",
        SemiColon = ";",
        Quote = "'",
        Comma = ",",
        Period = ".",
        FwdSlash = "/",

        KPZero = "kp0",
        KPOne = "kp1",
        KPTwo = "kp2",
        KPThree = "kp3",
        KPFour = "kp4",
        KPFive = "kp5",
        KPSix = "kp6",
        KPSeven = "kp7",
        KPEight = "kp8",
        KPNine = "kp9",
        KPPeriod = "kp.",
        KPSlash = "kp/",
        KPMul = "kp*",
        KPMinus = "kp-",
        KPPlus = "kp+",
        KPEnter = "kpenter",
        KPEquals = "kp=",

        LCtrl = "lctrl",
        LShift = "lshift",
        LAlt = "lalt",
        LGui = "lgui",
        RCtrl = "rctrl",
        RShift = "rshift",
        RAlt = "ralt",
        RGui = "rgui",
        CapsLock = "capslock",
        ScrollLock = "scrolllock",
        NumLock = "numlock",
    },
}
